### ISSUE TITLE
From chaos to normal (Artem)

### ISSUE THREAD

**Issue by Zimtir** [Zimtir/UniumGame#16]
Need do normalize our project , delete need not files, rename classes to normal names etc.

**Comment by TowarishArtem** [comment]
May be I late on 2-3 weeks, but I tried to remember all, what learned in last year. To my regret I found that my English is very bad, but I tried to write this program on English. I hope, with time I learn English better. But the program: I sorted cod on classes and in classes I tried also restore order. But isn't all. I make sound, some visual execution, learned about new function, decided some logic problems, and drink some tea :-)
